# Generated by Django 4.2.2 on 2026-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='None', max_length=10, null=True),
        ),
    ]
