# Generated by Django 4.2.2 on 2026-09-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('base', '0002_appointment_doctor_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='patient.patient'),
        ),
    ]
