# Generated by Django 4.2.2 on 2026-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
